/*
 * Copyright (c) 2026 Nuvoton Technology Corporation.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DRIVERS_MISC_NPCX_SHM_NPCX_SHM_H_
#define ZEPHYR_INCLUDE_DRIVERS_MISC_NPCX_SHM_NPCX_SHM_H_

#include <zephyr/device.h>
#include <zephyr/sys/util.h>
#include <zephyr/toolchain.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief SHM window identifiers.
 */
enum npcx_shm_window {
	NPCX_SHM_WINDOW_1 = 1,
	NPCX_SHM_WINDOW_2 = 2,
	NPCX_SHM_WINDOW_3 = 3,
	NPCX_SHM_WINDOW_4 = 4,
	NPCX_SHM_MAX_WINDOWS = 4,
};

/**
 * @brief Core interrupt mask bits. 
 * Used in struct npcx_shm_window_config.core_interrupts_mask to enable/disable core interrupts.
 * Also used in the callback function.
 */
#define NPCX_SHM_INT_ON_HOST_RD_CORE_OFFSET BIT(0)
#define NPCX_SHM_INT_ON_HOST_WR_HOST_OFFSET BIT(1)
#define NPCX_SHM_INT_ON_HOST_WR_SEMAPHORE   BIT(2)

/**
 * @brief Host-offset IRQ/SMI mask bits. 
 * Used in struct npcx_shm_window_config.host_interrupts_mask 
 * to enable/disable host interrupts.
 */
#define NPCX_SHM_IRQ_CORE_RD_FROM_HOST_OFFSET BIT(0)
#define NPCX_SHM_IRQ_CORE_WR_TO_CORE_OFFSET   BIT(1)
#define NPCX_SHM_SMI_CORE_RD_FROM_HOST_OFFSET BIT(4)
#define NPCX_SHM_SMI_CORE_WR_TO_CORE_OFFSET   BIT(5)
#define NPCX_SHM_IRQ_CORE_WR_TO_SEMAPHOR      BIT(6)
#define NPCX_SHM_SMI_CORE_WR_TO_SEMAPHOR      BIT(7)

/**
 * @brief SHM interrupt source selector used by interrupt_control().
 */
enum npcx_shm_interrupt_type {
	NPCX_SHM_INT_SEMAPHORE,
	NPCX_SHM_INT_CORE_OFFSET_ON_HOST_RD,
	NPCX_SHM_INT_CORE_OFFSET_ON_HOST_WR,
	NPCX_SHM_INT_HOST_OFFSET_IRQ_RD,
	NPCX_SHM_INT_HOST_OFFSET_IRQ_WR,
	NPCX_SHM_INT_HOST_OFFSET_SMI_RD,
	NPCX_SHM_INT_HOST_OFFSET_SMI_WR,
};

/**
 * @brief Callback invoked on SHM interrupt events.
 *
 * @param status Packed interrupt status bits generated by the driver ISR.
 */
typedef void (*npcx_shm_callback_t)(uint8_t status);

/**
 * @brief Unified SHM window configuration.
 *
 * This structure is consumed by npcx_shm_window_config() to configure
 * callback routing, semaphore behavior, window base/size/protection,
 * offsets, and offset-related interrupt masks.
 */
struct npcx_shm_window_config {
	/** Callback for SHM interrupt status notifications.                   */
	npcx_shm_callback_t callback;
	/** Window base address in RAM. Must be align to window_size.          */
	uint32_t window_base;
	/** Window size in bytes. Form 8 bytes to 4KB.                         *
	 *  Allowed values must be a powers of 2 (8,16,32,...4KB)              */
	uint16_t window_size;
	/** bitMask representing the access Protection                         *
	  * if a bit is set to 1 - the specific aread is protected.            *
	  * if a bit is set to 0 - the specific aread is not protected         *
	  * - Bit 0  = Write Protect the first (lower) 1/8 of the RAM window   *
	  * - Bit 1  = Write Protect the second 1/8 of the RAM window          *
	  * - Bit 2  = Write Protect the 3rd 1/8 of the RAM window             *
	  * - Bit 3  = Write Protect the 4th 1/8 of the RAM window             *
	  * - Bit 4  = Write Protect the 5th 1/8 of the RAM window             *
	  * - Bit 5  = Write Protect the 6th 1/8 of the RAM window             *
	  * - Bit 6  = Write Protect the 7th 1/8 of the RAM window             *
	  * - Bit 7  = Write Protect the 8th 1/8 of the RAM window             *
	  * - Bit 8  = Read Protect the first (lower) 1/8 of the RAM window    *
	  * - Bit 9  = Read Protect the second 1/8 of the RAM window           *
	  * - Bit 10 = Read Protect the 3rd 1/8 of the RAM window              *
	  * - Bit 11 = Read Protect the 4th 1/8 of the RAM window              *
	  * - Bit 12 = Read Protect the 5th 1/8 of the RAM window              *
	  * - Bit 13 = Read Protect the 6th 1/8 of the RAM window              *
	  * - Bit 14 = Read Protect the 7th 1/8 of the RAM window              *
	  * - Bit 15 = Read Protect the 8th 1/8 of the RAM window              */
	uint16_t window_protection_mask;
	/** Set the "Core offset" from the windows base.                        *
      *  A core WRITE to this offset can generate an IRQ/SMI to the host    *
      *  A host READ from this offset can generate an Interrupt to the core */
	uint16_t core_offset;
	/** Set Host offset from the window base.                               *
	  * A host WRITE to this offset can generate an Interrupt to the core   *
	  * A core READ from this offset can generate an IRQ/SMI to the host    */
	uint16_t host_offset;
	/** bitMask representing if Core Offset interrutpt is enabled/disabled  *
	  * If a bit is set to 1 - the specific interrutpt is enabled           *
	  * If a bit is set to 0 - the specific interrutpt is disabled          *
	  * bit 0 NPCX_SHM_OFFSET_INT_ON_HOST_RD_CORE_OFFSET                    *
	  *       Interrupt on host read from core offset                       *
	  * bit 1 NPCX_SHM_OFFSET_INT_ON_HOST_WR_HOST_OFFSET                    *
	  *       Interrupt on host write to host offset                        *
	  * bit 2 NPCX_SHM_INT_ON_HOST_WR_SEMAPHORE                             *
	  *       Interrupt on host access to the semaphore register            */
	uint8_t core_interrupts_mask;
	/** bitMask representing if HOST IRQ or SMI is enabled/disabled         *
	  * If a bit is set to 1 - the specific interrutpt is enabled           *
	  * If a bit is set to 0 - the specific interrutpt is disabled          *
	  * bit 0 NPCX_SHM_IRQ_CORE_RD_FROM_HOST_OFFSET                         *
	  *       Enable IRQ on core read from host offset.                     *
	  * bit 1 NPCX_SHM_IRQ_CORE_WR_TO_CORE_OFFSET                           *
	  *       Enable IRQ on core write to core offset.                      *
	  * bit 2,3 not used                                                    *
	  * bit 4 NPCX_SHM_SMI_CORE_RD_FROM_HOST_OFFSET                         *
	  *       Enable SMI on core read from host offset.                     *
	  * bit 5 NPCX_SHM_SMI_CORE_WR_TO_CORE_OFFSET                           *
	  *       Enable SMI on core write to core offset.                      *
	  * bit 6 NPCX_SHM_IRQ_CORE_WR_TO_SEMAPHOR                              *
	  *       Enable host IRQ on core write to semaphore register.          *
	  * bit 7 NPCX_SHM_SMI_CORE_WR_TO_SEMAPHOR                              *
	  *       Enable host SMI on core write to semaphore register.          */
	uint8_t host_interrupts_mask;
};

__subsystem struct npcx_shm_driver_api {
	void (*window_config)(const struct device *dev,
		     const struct npcx_shm_window_config *cfg);
	void (*interrupt_control)(const struct device *dev,
		     enum npcx_shm_interrupt_type type,
		     bool enable);
	uint8_t (*semaphore_read)(const struct device *dev);
	void (*semaphore_write)(const struct device *dev,
			  uint8_t value);
};


/**
 * @brief Apply unified SHM window configuration.
 *
 * @param dev SHM window device.
 * @param cfg Pointer to full window configuration.
 */
static inline void npcx_shm_window_config(const struct device *dev,
				  const struct npcx_shm_window_config *cfg)
{
	const struct npcx_shm_driver_api *api =
		(const struct npcx_shm_driver_api *)dev->api;

	api->window_config(dev, cfg);
}

/**
 * @brief Enable or disable one SHM interrupt source.
 *
 * @param dev SHM window device.
 * @param type Interrupt source selector.
 * @param enable true to enable, false to disable.
 */
static inline void npcx_shm_interrupt_control(const struct device *dev,
				     enum npcx_shm_interrupt_type type,
				     bool enable)
{
	const struct npcx_shm_driver_api *api =
		(const struct npcx_shm_driver_api *)dev->api;

	api->interrupt_control(dev, type, enable);
}

/**
 * @brief Read the current semaphore value for this SHM window.
 *
 * @param dev SHM window device.
 * @return uint8_t Current SHAWx_SEM value.
 */
static inline uint8_t npcx_shm_semaphore_read(const struct device *dev)
{
	const struct npcx_shm_driver_api *api =
		(const struct npcx_shm_driver_api *)dev->api;

	return api->semaphore_read(dev);
}

/**
 * @brief Write a semaphore value for this SHM window.
 *
 * @param dev SHM window device.
 * @param value Value written to SHAWx_SEM.
 */
static inline void npcx_shm_semaphore_write(const struct device *dev,
				    uint8_t value)
{
	const struct npcx_shm_driver_api *api =
		(const struct npcx_shm_driver_api *)dev->api;

	api->semaphore_write(dev, value);
}

#ifdef __cplusplus
}
#endif

#endif /* ZEPHYR_INCLUDE_DRIVERS_MISC_NPCX_SHM_NPCX_SHM_H_ */
